
// Auto-generated scraper for kings_theatre
// Generated by exploratory self-healer

import { initStagehand, openBrowserbaseSession, createStandardSchema, scrollToBottom, capturePageScreenshot } from '../lib/scraper-utils.js';
import { extractEventsFromPage } from '../lib/scraper-actions.js';
import { logScrapingResults, saveEventsToDatabase, handleScraperError } from '../lib/scraper-persistence.js';

const StandardEventSchema = createStandardSchema({ eventLocationDefault: 'Kings Theatre' });

export async function scrapeKingsTheatre() {
  const stagehand = await initStagehand({ env: 'BROWSERBASE' });
  const page = stagehand.page;

  try {
    console.log("Stagehand Session Started");
    console.log("Watch live:", stagehand.browserbaseSessionID);
    openBrowserbaseSession(stagehand.browserbaseSessionID);

    // Navigate to page
    await page.goto("https://www.kingstheatre.com/events/", {
      waitUntil: 'domcontentloaded',
      timeout: 60000
    });
    await page.waitForTimeout(3000);

    // Discovered interaction pattern:
    
    // click Show more button
    console.log("click Show more button...");
    try {
      await page.act("click Show more button");
      await page.waitForTimeout(2000);
    } catch (e) {
      console.log("Action failed (continuing):", e.message);
    }

    // Scroll to load more content
    await scrollToBottom(page);
    await page.waitForTimeout(2000);

    // Take screenshot for verification
    await capturePageScreenshot(page, 'kings_theatre');

    // Extract events
    const result = await extractEventsFromPage(
      page,
      "Extract all visible events with their names, dates, times (if shown), descriptions, and URLs",
      StandardEventSchema,
      { sourceName: 'kings_theatre' }
    );

    const events = result.events.map(e => ({
      ...e,
      eventLocation: "Kings Theatre"
    }));

    logScrapingResults(events, 'Kings Theatre');

    if (events.length > 0) {
      await saveEventsToDatabase(events, 'kings_theatre');
    }

    return { events };

  } catch (error) {
    await handleScraperError(error, page, 'Kings Theatre');
  } finally {
    await stagehand.close();
  }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  scrapeKingsTheatre();
}

export default scrapeKingsTheatre;
